### ISSUE TITLE
用 UID 倒推时区的方法需要针对十位数 UID 做改良。

### ISSUE THREAD

**Issue by ShikiSuen** [moyanj/UIGF-Upgrader#1]
下述两处 UID 处理没有考虑到 UID 是十位数的情况：

https://github.com/moyanj/UIGF-Upgrader/blob/03ff951e674aab3af23452724ae59deee12beedb/conv.py#L27-L34

https://github.com/moyanj/UIGF-Upgrader/blob/03ff951e674aab3af23452724ae59deee12beedb/conv.py#L57-L63

正确处理方法是：如果是十位数 UID，先去掉第十位数，再当九位数 UID 处理。
<img width="546" alt="image" src="https://github.com/user-attachments/assets/8aeed9ed-139c-46fd-8c6a-524929cc4504">

**Comment by moyanj** [comment]
已修复
